name       : perl-class-factory-util
version    : 1.7
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Class-Factory-Util-1.7.tar.gz : 6c516b445b44f87363fb3a148431d31e9ecb5e6f21fb6481c89b2406b6692e26
license    : Artistic-2.0
component  : programming.perl
summary    : Provide utility methods for factory classes
description: |
    Provide utility methods for factory classes
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
